//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Bán_Hàng_Cafa
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonChiTiet
    {
        public int id { get; set; }
        public int idHoaDon { get; set; }
        public int idThucAn { get; set; }
        public short soluong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual ThucAn ThucAn { get; set; }
    }
}
